// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Funciones", b =>
                {
                    b.Property<int>("FuncionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("FuncionId");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId");

                    b.ToTable("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Generos", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Nombre = "Acción"
                        },
                        new
                        {
                            GeneroId = 2,
                            Nombre = "Aventuras"
                        },
                        new
                        {
                            GeneroId = 3,
                            Nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            GeneroId = 4,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            GeneroId = 5,
                            Nombre = "Documental"
                        },
                        new
                        {
                            GeneroId = 6,
                            Nombre = "Drama"
                        },
                        new
                        {
                            GeneroId = 7,
                            Nombre = "Fantasia"
                        },
                        new
                        {
                            GeneroId = 8,
                            Nombre = "Musical"
                        },
                        new
                        {
                            GeneroId = 9,
                            Nombre = "Suspense"
                        },
                        new
                        {
                            GeneroId = 10,
                            Nombre = "Terror"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Peliculas", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeliculaId"));

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PeliculaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            GeneroId = 4,
                            Poster = "https://i.imgur.com/Qdd6klb.jpg",
                            Sinopsis = "El cirujano Danny decide contratar a su ayudante Katherine, una madre soltera con hijos, para que finjan ser su familia. Su intención es demostrarle a Palmer que su amor por ella es tan grande que está a punto de divorciarse de su mujer.",
                            Titulo = "Una esposa de mentira",
                            Trailer = "https://www.youtube.com/watch?v=xuZnmYjAKww"
                        },
                        new
                        {
                            PeliculaId = 2,
                            GeneroId = 3,
                            Poster = "https://i.imgur.com/xz1PBy0.jpg",
                            Sinopsis = "En un futuro prohibido tener más de un hijo, seis hermanas fingen ser la misma para escapar del Gobierno y buscar a la séptima hermana desaparecida.",
                            Titulo = "¿Qué le pasó a Lunes?",
                            Trailer = "https://www.youtube.com/watch?v=sRIYLZJqbEY"
                        },
                        new
                        {
                            PeliculaId = 3,
                            GeneroId = 1,
                            Poster = "https://i.imgur.com/gWGCYdr.jpg",
                            Sinopsis = "Un exagente de la DEA regresa a la acción para salvar a su hija y a su nueva ciudad de un psicópata que vende drogas.",
                            Titulo = "Línea de fuego",
                            Trailer = "https://www.youtube.com/watch?v=zHrnF621ggQ"
                        },
                        new
                        {
                            PeliculaId = 4,
                            GeneroId = 5,
                            Poster = "https://i.imgur.com/Q2eeSOC.png",
                            Sinopsis = "Un documental sobre la ciberseguridad y se sumerge en uno de los mayores ciberataques, el objetivo era apropiarse de casi mil millones de dólares. En 2016, el Banco Central de Bangladés sufrió un robo de 81 millones de dólares.",
                            Titulo = "El robo de mil millones de dolares",
                            Trailer = "https://www.youtube.com/watch?v=4zv56MUXgw8"
                        },
                        new
                        {
                            PeliculaId = 5,
                            GeneroId = 4,
                            Poster = "https://i.imgur.com/VJGTWKG.jpg",
                            Sinopsis = "Cady Heron ha sido criada en la selva africana. Sus padres zoólogos intentaron educarla en las leyes de la naturaleza, pero al cumplir quince años, debe ir al instituto y adaptarse a su nueva vida en Illinois.",
                            Titulo = "Mean Girls",
                            Trailer = "https://www.youtube.com/watch?v=oDU84nmSDZY"
                        },
                        new
                        {
                            PeliculaId = 6,
                            GeneroId = 10,
                            Poster = "https://i.imgur.com/HKpufD5.jpg",
                            Sinopsis = "M3GAN es una maravilla de la inteligencia artificial, una muñeca realista diseñada para ser la mejor compañera de los niños. Puede escuchar, observar y aprender, convirtiéndose en amiga, profesora, compañera de juegos y protectora.",
                            Titulo = "M3GAN",
                            Trailer = "https://www.youtube.com/watch?v=1vTbhymPSA4"
                        },
                        new
                        {
                            PeliculaId = 7,
                            GeneroId = 1,
                            Poster = "https://i.imgur.com/tGJwzGc.jpg",
                            Sinopsis = "Los héroes de Marvel deben reunirse para deshacer las acciones de Thanos y restaurar el equilibrio en el universo.",
                            Titulo = "Avengers: Endgame",
                            Trailer = "https://www.youtube.com/watch?v=PyakRSni-c0"
                        },
                        new
                        {
                            PeliculaId = 8,
                            GeneroId = 9,
                            Poster = "https://i.imgur.com/rRAMOZR.jpg",
                            Sinopsis = "Un cómico fallido se sumerge en la locura y se convierte en el infame villano Joker en Gotham City.",
                            Titulo = "Joker",
                            Trailer = "https://www.youtube.com/watch?v=zAGVQLHvwOY"
                        },
                        new
                        {
                            PeliculaId = 9,
                            GeneroId = 7,
                            Poster = "https://i.imgur.com/U6aTYJU.jpg",
                            Sinopsis = "Los juguetes de Andy, encabezados por Woody el vaquero, cobran vida cuando nadie está mirando. Pero cuando un nuevo juguete, Buzz Lightyear, llega al grupo, Woody se siente amenazado y se embarcan en una aventura para regresar a casa.",
                            Titulo = "Toy Story",
                            Trailer = "https://www.youtube.com/watch?v=v-PjgYDrg70"
                        },
                        new
                        {
                            PeliculaId = 10,
                            GeneroId = 6,
                            Poster = "https://i.imgur.com/333XNA8.jpg",
                            Sinopsis = "Un banquero es condenado por un asesinato que no cometió y pasa décadas en la prisión de Shawshank, donde forma una amistad única con otro recluso.",
                            Titulo = "The Shawshank Redemption",
                            Trailer = "https://www.youtube.com/watch?v=6hB3S9bIaco"
                        },
                        new
                        {
                            PeliculaId = 11,
                            GeneroId = 8,
                            Poster = "https://i.imgur.com/Yo52ZWJ.jpg",
                            Sinopsis = "Un pianista y una actriz en ciernes se enamoran en Los Ángeles mientras persiguen sus sueños artísticos.",
                            Titulo = "La La Land",
                            Trailer = "https://www.youtube.com/watch?v=0pdqf4P9MB8"
                        },
                        new
                        {
                            PeliculaId = 12,
                            GeneroId = 5,
                            Poster = "https://i.imgur.com/ACXFboh.jpg",
                            Sinopsis = "Este documental revela la verdad detrás de la cautividad de las orcas en parques acuáticos y la peligrosidad de mantenerlas en cautiverio.",
                            Titulo = "Blackfish",
                            Trailer = "https://www.youtube.com/watch?v=fLOeH-Oq_1Y"
                        },
                        new
                        {
                            PeliculaId = 13,
                            GeneroId = 2,
                            Poster = "https://i.imgur.com/zFvBmAK.jpg",
                            Sinopsis = "El intrépido arqueólogo Indiana Jones se embarca en una búsqueda para encontrar el Santo Grial antes que los nazis.",
                            Titulo = "Indiana Jones and the Last Crusade",
                            Trailer = "https://www.youtube.com/watch?v=a6JB2suJYHM"
                        },
                        new
                        {
                            PeliculaId = 14,
                            GeneroId = 2,
                            Poster = "https://i.imgur.com/1oE0Ud8.jpg",
                            Sinopsis = "Un científico descubre una forma de viajar al centro de la Tierra y se embarca en una emocionante aventura subterránea junto a su sobrino y un guía local.",
                            Titulo = "Viaje al centro de la tierra",
                            Trailer = "https://www.youtube.com/watch?v=ytDcArTr0CI"
                        },
                        new
                        {
                            PeliculaId = 15,
                            GeneroId = 2,
                            Poster = "https://i.imgur.com/xwJNL4Z.jpg",
                            Sinopsis = "Un grupo de personas queda atrapado en una isla donde se han creado dinosaurios clonados y deben luchar por su supervivencia.",
                            Titulo = "Jurassic Park",
                            Trailer = "https://www.youtube.com/watch?v=lc0UehYemQA"
                        },
                        new
                        {
                            PeliculaId = 16,
                            GeneroId = 10,
                            Poster = "https://i.imgur.com/vG8P2jY.jpg",
                            Sinopsis = "Basada en hechos reales, una familia experimenta fenómenos paranormales en su nueva casa y busca ayuda de investigadores paranormales.",
                            Titulo = "El Conjuro",
                            Trailer = "https://www.youtube.com/watch?v=k10ETZ41q5o"
                        },
                        new
                        {
                            PeliculaId = 17,
                            GeneroId = 9,
                            Poster = "https://i.imgur.com/lYGE3LJ.jpg",
                            Sinopsis = "Un hombre se convierte en el principal sospechoso cuando su esposa desaparece y las evidencias sugieren que él podría estar involucrado.",
                            Titulo = "Gone Girl",
                            Trailer = "https://www.youtube.com/watch?v=2-_-1nJf8Vg"
                        },
                        new
                        {
                            PeliculaId = 18,
                            GeneroId = 8,
                            Poster = "https://i.imgur.com/ZrRH8z5.jpg",
                            Sinopsis = "La historia de personajes cuyas vidas se entrelazan en la Francia del siglo XIX, luchando por la justicia y la redención.",
                            Titulo = "Les Misérables",
                            Trailer = "https://www.youtube.com/watch?v=IuEFm84s4oI"
                        },
                        new
                        {
                            PeliculaId = 19,
                            GeneroId = 5,
                            Poster = "https://i.imgur.com/xRZC4Ji.jpg",
                            Sinopsis = "Este documental sigue la epopeya de los pingüinos emperadores mientras luchan por sobrevivir y criar a sus crías en la Antártida.",
                            Titulo = "March of the Penguins",
                            Trailer = "https://www.youtube.com/watch?v=ohL8rF_jluA"
                        },
                        new
                        {
                            PeliculaId = 20,
                            GeneroId = 6,
                            Poster = "https://i.imgur.com/LeQf3gP.jpg",
                            Sinopsis = "Matt Turner, un hombre de negocios estadounidense que vive en Berlín y que se encuentra en una carrera contrarreloj para salvar a su familia y su propia vida.",
                            Titulo = "Contrarreloj",
                            Trailer = "https://www.youtube.com/watch?v=T7HlHI4S-MY"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Salas", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaId = 1,
                            Capacidad = 5,
                            Nombre = "2D"
                        },
                        new
                        {
                            SalaId = 2,
                            Capacidad = 15,
                            Nombre = "3D"
                        },
                        new
                        {
                            SalaId = 3,
                            Capacidad = 35,
                            Nombre = "4D"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tickets", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FuncionId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.HasIndex("FuncionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Funciones", b =>
                {
                    b.HasOne("Domain.Entities.Peliculas", "Pelicula")
                        .WithMany("Funciones")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Salas", "Sala")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Domain.Entities.Peliculas", b =>
                {
                    b.HasOne("Domain.Entities.Generos", "Genero")
                        .WithMany("Peliculas")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Domain.Entities.Tickets", b =>
                {
                    b.HasOne("Domain.Entities.Funciones", "Funcion")
                        .WithMany("Tickets")
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcion");
                });

            modelBuilder.Entity("Domain.Entities.Funciones", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Generos", b =>
                {
                    b.Navigation("Peliculas");
                });

            modelBuilder.Entity("Domain.Entities.Peliculas", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Salas", b =>
                {
                    b.Navigation("Funciones");
                });
#pragma warning restore 612, 618
        }
    }
}
